name: ubuntu-welcome
version: git
summary: Ubuntu Welcome
description: Ubuntu Welcome
confinement: strict
base: core22
grade: stable
license: GPL-3.0+
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64

apps:
  ubuntu-welcome:
    command: bin/ubuntu_welcome
    extensions: [gnome]
    plugs:
      - accounts-service
      - gsettings
      - locale-control
      - shutdown
      - time-control
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin:$PATH
      LOG_LEVEL: debug

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.10.5
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  ubuntu-welcome:
    after: [flutter-git]
    plugin: nil
    source: .
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin/lib
      cd packages/ubuntu_welcome
      flutter pub get
      flutter build linux --release -v
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

slots:
  ubuntu-welcome:
    interface: dbus
    bus: session
    name: com.canonical.ubuntu_welcome
