// Mocks generated by Mockito 5.0.14 from annotations
// in ubuntu_desktop_installer/test/services/gschema_compiler_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;
import 'dart:io' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ubuntu_desktop_installer/services/process_runner.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeProcessResult_0 extends _i1.Fake implements _i2.ProcessResult {}

/// A class which mocks [ProcessRunner].
///
/// See the documentation for Mockito's code generation for more information.
class MockProcessRunner extends _i1.Mock implements _i3.ProcessRunner {
  MockProcessRunner() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProcessResult> run(
          String? executable, List<String>? arguments) =>
      (super.noSuchMethod(Invocation.method(#run, [executable, arguments]),
              returnValue:
                  Future<_i2.ProcessResult>.value(_FakeProcessResult_0()))
          as _i4.Future<_i2.ProcessResult>);
  @override
  String toString() => super.toString();
}
