name: ubuntu_test
description: Shared test extensions and mocks.
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  build_runner: ^2.1.1
  effective_dart: ^1.3.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  gsettings: ^0.2.0
  mockito: 5.0.14
  subiquity_client:
    git:
      url: https://github.com/canonical/ubuntu-desktop-installer.git
      path: packages/subiquity_client
  ubuntu_wizard:
    git:
      url: https://github.com/canonical/ubuntu-desktop-installer.git
      path: packages/ubuntu_wizard

dependency_overrides:
  subiquity_client:
    path: ../subiquity_client
  ubuntu_localizations:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_localizations
  ubuntu_wizard:
    path: ../ubuntu_wizard
