# based on https://github.com/ogra1/snapd-docker
FROM ubuntu:22.04

ENV container docker
ENV PATH "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV DEBIAN_FRONTEND noninteractive
ENV LIVE_RUN 1
ENV XDG_RUNTIME_DIR "/run/user/0"

RUN apt-get update
RUN apt-get install -y fuse init snapd squashfuse sudo

RUN dpkg-divert --local --rename --add /sbin/udevadm
RUN ln -s /bin/true /sbin/udevadm
RUN systemctl enable snapd snapd.seeded
VOLUME ["/sys/fs/cgroup"]
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]

RUN apt-get install -y cloud-init

RUN apt-get install -y dbus git libgtk-3-0 libegl1 network-manager python3 tree upower xvfb

RUN apt-get install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip
RUN git clone --branch stable --depth 1 https://github.com/flutter/flutter.git /usr/libexec/flutter
RUN ln -s /usr/libexec/flutter/bin/flutter /usr/bin/flutter
RUN flutter config --enable-linux-desktop
