name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  # build:
  #   runs-on: ubuntu-20.04
  #   steps:
    
  #   - uses: actions/checkout@v2
  #     with:
  #       submodules: recursive

  #   - uses: subosito/flutter-action@v1
  #     with:
  #       channel: 'stable'

  #   - name: Enable Linux desktop support
  #     run: flutter config --enable-linux-desktop

  #   - name: Install Melos
  #     run: flutter pub global activate melos

  #   - name: Install lcov
  #     run: sudo apt update && sudo apt install lcov

  #   # subiquity

  #   - name: Get subiquity dependencies
  #     working-directory: ./packages/subiquity_client/subiquity
  #     run: sudo ./scripts/installdeps.sh

  #   - name: Check subiquity integration
  #     run: ./scripts/subiquity_integration

  #   # test all packages

  #   - name: Bootstrap workspace
  #     run: melos bootstrap
    
  #   - name: Run tests
  #     run: melos run coverage

  #   - name: Upload coverage results
  #     uses: codecov/codecov-action@v1
  #     with:
  #       token: ${{secrets.CODECOV_TOKEN}}

  analyze:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2

    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: Enable Linux desktop support
      run: flutter config --enable-linux-desktop

    - name: Install Melos
      run: flutter pub global activate melos

    - name: Bootstrap workspace
      run: melos bootstrap

    # - name: Check for any formatting issues
    #   run: melos run format

    # - name: Check for any analyzer issues
    #   run: melos run analyze

    # - name: Check for any code generation issues
    #   run: melos run generate

    - name: Check for any l10n generation issues
      run: melos run gen-l10n

    - name: Detect changes
      id: detect-changes
      run: |
        git_status=$(git status --porcelain)
        git_diff=$(git add -N && git diff)
        echo "::set-output name=git_status::${git_status//$'\n'/'%0A'}"
        echo "::set-output name=git_diff::${git_diff//$'\n'/'%0A'}"

    - name: Post comment
      if: github.event_name == 'pull_request' && steps.detect-changes.outputs.git_status != ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{github.event.pull_request.number}}
        body: |-
          Warning: the following generated files may be outdated or untracked:
          ```
          ${{steps.detect-changes.outputs.git_status}}
          ```
          <details><summary>Details:</summary>

          ```diff
          ${{steps.detect-changes.outputs.git_diff}}
          ```
          </details>
