name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # build:
  #   runs-on: ubuntu-20.04
  #   steps:
    
  #   - uses: actions/checkout@v2
  #     with:
  #       submodules: recursive

  #   - uses: subosito/flutter-action@v1
  #     with:
  #       channel: 'stable'

  #   - name: Enable Linux desktop support
  #     run: flutter config --enable-linux-desktop

  #   - name: Install Melos
  #     run: flutter pub global activate melos

  #   - name: Install lcov
  #     run: sudo apt update && sudo apt install lcov

  #   # subiquity

  #   - name: Get subiquity dependencies
  #     working-directory: ./packages/subiquity_client/subiquity
  #     run: sudo ./scripts/installdeps.sh

  #   - name: Check subiquity integration
  #     run: ./scripts/subiquity_integration

  #   # test all packages

  #   - name: Bootstrap workspace
  #     run: melos bootstrap
    
  #   - name: Run tests
  #     run: melos run coverage

  #   - name: Upload coverage results
  #     uses: codecov/codecov-action@v1
  #     with:
  #       token: ${{secrets.CODECOV_TOKEN}}

  # analyze:
  #   runs-on: ubuntu-20.04
  #   steps:

  #   - uses: actions/checkout@v2

  #   - uses: subosito/flutter-action@v1
  #     with:
  #       channel: 'stable'

  #   - name: Enable Linux desktop support
  #     run: flutter config --enable-linux-desktop

  #   - name: Install Melos
  #     run: flutter pub global activate melos

  #   - name: Bootstrap workspace
  #     run: melos bootstrap

  #   - name: Check for any formatting issues
  #     run: melos run format

  #   - name: Check for any analyzer issues
  #     run: melos run analyze

  generate:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2

    # - uses: subosito/flutter-action@v1
    #   with:
    #     channel: 'stable'

    # - name: Enable Linux desktop support
    #   run: flutter config --enable-linux-desktop

    # - name: Install Melos
    #   run: flutter pub global activate melos

    # - name: Bootstrap workspace
    #   run: melos bootstrap

    # - name: Generate source code
    #   run: melos run generate

    # - name: Generate l10n files
    #   run: melos run gen-l10n

    - name: Warn about outdated generated files
      if: github.event_name == 'pull_request'
      run: |
        echo modification >> README.md
        rm LICENSE
        touch new-file

        if [ -n "$(git status --porcelain)" ]; then
          outdated=$(git diff --stat)
          if [ -n "$outdated" ]; then
            outdated="${outdated//'%'/'%25'}"
            outdated="${outdated//$'\n'/'%0A'}"
            outdated="${outdated//$'\r'/'%0D'}"
            echo "::warning ::Outdated files:%0A$outdated"
          fi
          untracked=$(git ls-files --others --exclude-standard)
          if [ -n "$untracked" ]; then
            untracked="${untracked//'%'/'%25'}"
            untracked="${untracked//$'\n'/'%0A'}"
            untracked="${untracked//$'\r'/'%0D'}"
            echo "::warning ::Untracked files:%0A$untracked"
          fi
          echo ""
          echo ""
          git diff
          exit 1
        fi

    - name: Commit outdated generated files
      if: github.event_name == 'workflow_dispatch'
      uses: actions-js/push@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        message: 'Regenerate files'
